### PR TITLE
GHA: add initial workflow for building the tools

### PR DESCRIPTION
**Pull request by compnerd**
Introduce a build system and build workflow for building dump_syms for Windows. This is to enable us to consider breakpad symbols for Arc as a means of getting undecorated symbols.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
@compnerd you may want to look at my repo at [snxd/breakpad](https://github.com/snxd/breakpad) which already has that.

**Comment by compnerd** [comment]
@nmoinvaz thanks for the pointer!  Would that also be accepting of "arbitrary" changes? (Namely extensions to support other languages).

**Comment by nmoinvaz** [comment]
What did you have in mind? There is already a breakpad port elsewhere that is written in rust.

**Comment by compnerd** [comment]
@nmoinvaz extensions to support Swift.

**Comment by nmoinvaz** [comment]
I don't have any use for that. I recommend just forking what I have if you need it. We also do have our own interface, and it is separate from our breaking fork.

**Pull request closed without merging**
